pipeline {
    agent none

    stages {
        stage("build") {
            agent {
                docker { image  'ubuntu:latest' }
            }
            steps {
                sh 'echo $USER'
            }
        }
    }
}
